server.port: 0
spring:
  application:
    name: baz-sink
  cloud:
    function:
      definition: storeFoo
    stream:
      defaultBinder: rabbit
      bindings:
        storeFoo-in-0:
          destination: foo-result
          group: foo-result-group
          consumer:
            maxAttempts: 4
            backOffInitialInterval: 15000
            backOffMaxInterval: 60000
