apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: baz-sink
  description: Accelerator generated streaming application
  tags:
    - app-accelerator
    - java
    - spring
    - streaming
    - tanzu
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=baz-sink'
spec:
  type: service
  lifecycle: experimental
  owner: default-team
